title: OrdinaryJellyfish
description: ğŸ³ï¸â€ğŸŒˆ GAY AND PROUD JELLYFISH

twitter:
  username: UnseenJellyfish
social:
  name: Tristian Kelly
  links:
    - https://twitter.com/UnseenJellyfish
    - https://github.com/OrdinaryJellyfish

permalink: /:title

plugins:
  - jemoji
